# WC: build & push to Dockerhub
# aus:
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
# https://www.codebyamir.com/blog/publish-a-docker-image-to-private-docker-hub-repo-using-github-actions

name: Image-Push zu Dockerhub

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.vars.outputs.tag }}
